export default {
  status: '',
  token: localStorage.getItem('token') || '',
  user: {},
  groups: [],
  currentgroup: {},
  currentuser: {},
  playerShown: false,
  source: "",
  playing: false,
  next: "",
  prev: "",
  hasNext: false,
  hasPrev: false,
}
